In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
#print 1 to 5
print(arr[1:5])
#print every element 1 to 5 but not include last elemnt


[2 3 4 5]


In [2]:
print(arr[:4])

[1 2 3 4]


In [3]:
print(arr[4:])

[5 6 7 8 9]


In [4]:
#negative indexing
print(arr[-3:-1])

[7 8]


In [5]:
#2-d array slicing
arr1=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr1[0,1:2])

[2]


In [6]:
print(arr1[0,0:2])

[1 2]


In [7]:
print(arr1[1,0:2])

[7 8]


In [8]:
print(arr1[0:2,1:3])

[[2 3]
 [8 9]]
